---
title: "Desafio 5"
output: pdf
---

```{r, echo=FALSE, include=FALSE}
install.packages
```

```{r}
library(RSQLite)

db = dbConnect(SQLite(), 'disco.db')
db

```

```{r}
dbListTables(db)
```

```{r}
dbListFields(db,'albums')
```

```{r}
album_db = dbGetQuery(db,'SELECT * FROM albums')
head(album_db)

```

```{r}
dim(album_db)
```

```{r}
sql = 'SELECT trackid, name, composer, unitprice FROM tracks ORDER BY name'
res = dbGetQuery(db, sql)
head(res)
```

```{r}
sql = 'SELECT city FROM customers ORDER BY city'

ex3a = dbGetQuery(db, sql)
head(ex3a)

```

```{r}
dim(ex3a)

```

```{r}
sql = 'SELECT DISTINCT city FROM customers ORDER BY city'

ex3b = dbGetQuery(db, sql)
head(ex3b)
```

```{r}
dim(ex3b)

```

```{r}
sql = 'SELECT name, albumid FROM tracks WHERE albumid=1'

album = dbGetQuery(db, sql)
head(album)
```

```{r}
sql = 'SELECT name, albumid, mediatypeid FROM tracks WHERE mediatypeid = 1 OR mediatypeid = 2 ORDER BY name LIMIT 5'

ccomplex = dbGetQuery(db, sql)
head(ccomplex)
```

```{r}
sql = 'SELECT trackid, name, albumid FROM tracks WHERE albumid IN (SELECT albumid FROM albums WHERE artistid == 12)'

artista = dbGetQuery(db, sql)
head(artista)
```

```{r}
sql = "SELECT trackid, name FROM tracks WHERE name GLOB '?ere*'"
dbGetQuery(db, sql)[1:5,]

```

```{r}
sql = "SELECT trackid, name FROM tracks WHERE name GLOB '*[0-9]*'"
dbGetQuery(db, sql)[1:5,]
```

```{r}
sql = 'SELECT albumid, COUNT(trackid) FROM tracks GROUP BY albumid'
dbGetQuery(db, sql)[1:5,]
```

```{r}
sql = 'SELECT albumid, COUNT(trackid) FROM tracks WHERE albumid = 1 GROUP BY albumid'
dbGetQuery(db, sql)
```

```{r}
sql = 'SELECT trackid, name, title FROM tracks INNER JOIN albums ON tracks.albumid = albums.albumid'

dbGetQuery(db, sql)[1:5,]

```
